version: '3.9'

services:

  poc.admin.webapi:
    ports:
      - 5075:5075
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

