version: '3.9'
# docker-compose up --build
networks:
  app-network:
    driver: bridge

services:

# APIS BEGIN -----------------------------------------------------------------------------

  poc.twilio.api.webapi:
    image: ${DOCKER_REGISTRY-}poc.twilio.api.webapi
    container_name: poc.twilio.api.webapi
    restart: always
    build:
      context: .
      dockerfile: src/01-Presentation/Poc.Twilio.API/Dockerfile
    expose:
      - 5079
    ports:
      - 5079:5079
    links:
      - redis
      - mongoserver
    networks:
      - app-network
    depends_on:
      - redis
      - mongoserver

# APIS END -----------------------------------------------------------------------------

# DB BEGIN -----------------------------------------------------------------------------

  # Redis Cache Server
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass Poc2Minimal@Api
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - app-network

  mongoserver:
    image: mongo:latest
    container_name: mongoserver
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - app-network

# DB END -----------------------------------------------------------------------------

