name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - release
      - develop
  pull_request:
    branches:
      - main
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      rabbitmq:
        image: rabbitmq:management
        ports:
          - 5672:5672
          - 15672:15672
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: "@Poc2Minimal@Api"
        ports:
          - 1433:1433
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up .NET Core
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x

    # Restore dependencies for backend
    - name: Restore backend dependencies
      run: dotnet restore backend/API.Admin/API.Admin.csproj

    # # Restore dependencies for tests
    # - name: Restore test dependencies
    #   run: dotnet restore backend/API.Admin.Tests/API.Admin.Tests.csproj

    # Build the backend
    - name: Build backend
      run: dotnet build backend/API.Admin/API.Admin.csproj --configuration Release --no-restore

    # # Run tests for backend
    # - name: Run backend tests
    #   run: dotnet test backend/API.Admin.Tests/API.Admin.Tests.csproj --no-restore --verbosity normal

    # Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install dependencies for frontend
    - name: Install frontend dependencies
      working-directory: frontend/web.admin.react
      run: npm install

    # Build the frontend
    - name: Build frontend
      working-directory: frontend/web.admin.react
      run: npm run build

    # Deploy steps can be added here for backend and frontend

    # # Azure Login
    # - name: Azure Login
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    # # Deploy backend to Azure Web App
    # - name: Deploy backend to Azure Web App
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: <Your-App-Service-Name>
    #     slot-name: production
    #     package: backend/API.Admin/bin/Release/net8.0/publish

    # # Deploy frontend to Azure Static Web Apps
    # - name: Deploy frontend to Azure Static Web Apps
    #   uses: Azure/static-web-apps-deploy@v1
    #   with:
    #     azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     action: 'upload'
    #     app_location: 'frontend/web.admin.react'
    #     output_location: 'frontend/web.admin.react/build'

